### ISSUE TITLE
Invalid Holding Address 3049

### ISSUE THREAD

**Issue by CHOMNANP** [NModbus4/NModbus4#115]
I am trying to read modbus RTU holding reading from address over 3000 (my target adr is 43049), but it does not work. 

My device is Schneider 1250 Watt meter.

please help me to solve this problem.

                SerialPort port = new SerialPort("COM3");
                port.BaudRate = 9600;
                port.DataBits = 8;
                port.Parity = Parity.Even;
                port.StopBits = StopBits.One;
                port.ReadTimeout = 500;
                port.Open();

                // create modbus master
                IModbusSerialMaster master = ModbusSerialMaster.CreateRtu(port);

                byte slaveId = 11;
                ushort startAddress = 3049;
                ushort numRegisters = 1;

                // read five registers
                ushort[] registers = master.ReadHoldingRegisters(slaveId, startAddress, numRegisters);
                port.Close();
                for (int i = 0; i < numRegisters; i++)
                    Console.WriteLine("Register {0}={1}", startAddress + i, registers[i]);
               
                `

Error messsage
`Modbus.SlaveException: Exception of type 'Modbus.SlaveException' was thrown.
Function Code: 131
Exception Code: 2 - The data address received in the query is not an allowable address for the server (or slave). More specifically, the combination of reference number and transfer length is invalid. For a controller with 100 registers, the PDU addresses the first register as 0, and the last one as 99. If a request is submitted with a starting register address of 96 and a quantity of registers of 4, then this request will successfully operate (address-wise at least) on registers 96, 97, 98, 99. If a request is submitted with a starting register address of 96 and a quantity of registers of 5, then this request will fail with Exception Code 0x02 "Illegal Data Address" since it attempts to operate on registers 96, 97, 98, 99 and 100, and there is no register with address 100.
   at Modbus.IO.ModbusTransport.UnicastMessage[T](IModbusMessage message)
   at Modbus.Device.ModbusMaster.PerformReadRegisters(ReadHoldingInputRegistersRequest request)
   at Modbus.Device.ModbusMaster.ReadHoldingRegisters(Byte slaveAddress, UInt16 startAddress, UInt16 numberOfPoints)
   at meter_test1.Program.Main(String[] args) in c:\Users\Vong Sarak\Documents\Visual Studio 2013\Projects\meter_test1\meter_test1\Program.cs:line 41
`

**Comment by bkmr** [comment]
According to the [datasheet](http://download.schneider-electric.com/files?p_enDocType=User+guide&p_File_Id=1391297388&p_File_Name=EAV95451-02.pdf&p_Reference=EAV95451), holding register 3049 is of type `float`, therefore you must read at least 2 registers or the slave will reject your request.

You will then need to deserialise the 2 registers into a float type.
